spring.application.name=campuspyq

# ==========================
# PostgreSQL Configuration
# ==========================

spring.datasource.url=jdbc:postgresql://dpg-d9bt1h67r5hc739cta1g-a.oregon-postgres.render.com:5432/campuspyq
spring.datasource.username=campuspyq
spring.datasource.password=JAKo0bkQJUL1luPGb3IhNi1Od1eYwbhu
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================
# Hibernate / JPA
# ==========================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB


cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# ==========================
# Server
# ==========================

server.port=${PORT:8080}

# ==========================
# File Upload
# ==========================

file.upload-dir=uploads